README.md
simply adds the CI results badge and the link to [godoc](https://pkg.go.dev/github.com/AdRoll/baker) in the readme
=> Add CI and docs badges to the readme

upload/s3_integration_test.go, upload/s3_test.go
Add some integration tests of the s3 upload in order to fix the upload-topology interaction in stone.
A first test verifies the uploader uploads all produced files if we block on `topology.Wait`
A second test stops the topology (as a CTRL-C would do) and ensure all produced files are also uploaded
Just call `go test -race -run TestIntegrationS3 ./upload`
=> Add s3 upload integration tests

CHANGELOG.md, bench_test.go, filter/set_string_from_url_test.go, logline.go, logline_test.go, record.go, test_helper.go, topology.go
Add `Copy` method to the `Record` interface.
This is necessary for filters that want to create copies of a record.
Without that new method, one would have to call `src.ToText` followed by `dst.Parse` to make `dst` being a copy of `src` `Record`. This is what I call the naive solution.
The following benchmarks comparisons shows the optimized Copy vs the naive version:
name                  old time/op    new time/op    delta
LogLineCopy/set=0-8     7.94µs ± 8%    4.65µs ±10%  -41.43%  (p=0.000 n=15+15)
LogLineCopy/set=1-8     32.7µs ± 5%    30.8µs ± 6%   -5.86%  (p=0.000 n=13+15)
LogLineCopy/set=10-8    33.8µs ± 3%    30.6µs ± 5%   -9.56%  (p=0.000 n=14+15)
LogLineCopy/set=20-8    32.8µs ± 6%    30.1µs ± 4%   -8.03%  (p=0.000 n=15+15)
name                  old alloc/op   new alloc/op …
=> Add Record.Copy

CHANGELOG.md, README.md, input/kcl.go
Document technical decisions, parameters and high-level implementation of the KCL Baker input.
=> README: document KCL technical decisions/params

input/inputtest/logline.go
This is a very small addition to a test input:
It's now possible to set metatada to the records with the Logline test input
=> input/inputtest: add Metadata to Logline input

CHANGELOG.md, README.md, logline.go, stats.go, stats_test.go, topology.go
Make `baker.LogLine` more easily customizable.
LogLine hardcoded constants are now only used in `logline.go` so that if one copies that file to their project all continues to work.
Document how to do it in `README.md`
Describe what this pull request does.
=> Logline specialization

CHANGELOG.md, logline.go, test_helper.go
There was a bug in `logline.Copy`: when a logline were parsed and immediately copied (without setting any field), then the copy was wrong because `idx` was missing
I benchmarked the solution in this pr agains copying the whole logline (`*cpy = *l`) and this solution is a bit faster (~23000 ns/op vs ~26000 ns/op)
=> logline.Copy didn't copy the idx

content/en/docs/Core concepts/record_implementation.md, content/en/docs/How To/custom_record.md
Split `Record Implementation` page in 2
=> doc: split record page into 2

help_config.go, help_markdown.go
3 things here to optimize the markdown output when generating the components' pages for the doc site:
* prints the slice default when missing as it is often used into the already existing components (to have the same behavior)
* add double space to make a newline, as the website doesn't show a newline with only `\n`. Also, don't add a newline after `:` because in the website it creates an odd output in lists
* do not align to the center of the columns the name and the description, for a more readable output
=> improve help output for docs pages

CHANGELOG.md, baker_cli.go, config.go, config_test.go, examples/basic/main.go, examples/sharding/main.go, input/tcp_test.go, raw_output_test.go, topology.go, upload/s3_integration_test.go, user_config_test.go
This is another step in the direction of making baker a full-featured binary one can use without touching code.
This gives the possibilty to defined field mapping in TOML. What we call fIeld mapping is a two-way mapping from field indexes and field names.  
Before this change, one had to provide 2 function `FieldName` and `FieldByName` into baker.Components, even for super basic use of baker. Now you can specify this in TOML, from which 2 closures are generated and assigned into these 2 functions. This is done in `NewConfigFromTOML`.
=> Read field mapping from toml

CHANGELOG.md, README.md, config.go, config_test.go, desc.go, examples/advanced/main.go, examples/sharding/main.go, output/sqlite.go, output/sqlite_test.go, output/stats.go, stats.go, stats_test.go, topology.go
This replaces `FieldName func(baker.FieldIndex) string` with a simple slice called `FieldNames []string`
This is a tiny breaking change but it brings the following benefits:
- code is simpler to read and write (see modified examples),
- though not measured because it's not so important, but this is probably more performant
- overall it gives the possibility to know the maximum number of defined fields, by just doing len(FieldNames), which was impossible to do before, and needed some times.
- before, if the user provided an wrong index, the only way to return an error was to return an empty string, which has to be checked anyway. Now the user can avoid that by checking the index against the slice length, and if a wrong index is provided, go will panic with an out of bounds index message, …
=> Replace FieldName function to Fieldname slice

CHANGELOG.md, input/inpututils/fastreader.go, input/inpututils/fastreader_unix.go
Fix the building issues on Windows (#115).  
Now, the `FastGzReader` uses the [gzip reader](https://pkg.go.dev/compress/gzip#NewReader) of the go std by default. The previous optimization will be available only on Linux and Mac.
=> fix: building on windows

CHANGELOG.md, input/list_test.go
Fix `list_test` on windows. We use [file URI](https://en.wikipedia.org/wiki/File_URI_scheme) instead of Unix path, which permits us to be cross-platform and compatible with windows paths.
=> fix: path issue on tests on windows

config_test.go
The test case `duplicated field name`  of `Test_assignFieldMapping` does not correctly check the intended case because a Components is passed. The function will be stopped with the error `field indexes/names can't both be set in TOML and Components` and not `duplicated field name "baz"`.
Here the coverage screenshot:
=> fix: assignFieldMapping test skip a case

Dockerfile, Makefile
The alpine repository has an old version of HUGO, which do not correctly compile the web site.
This PR changes the Docker image with the HUGO official one.
=> fix: change docker image with hugo official one

filter/all.go
The ExpandJSON filter was not added to the all.go file
=> fix: add ExpandJSON to all.go

CHANGELOG.md, filter/all.go, filter/hash.go, filter/hash_test.go
The `Hash` filter hashes a field using a specified hash function and writes the value on another (or the same) field.
Hash function supported:
- md5
- sha256
It is also possible to encode the hash with _hexadecimal encoding_ to avoids encoding problems.
1. Add the `Hash` filter into a Baker TOML
2. Properly configure it
3. Run Baker
=> feat: add Hash filter

CHANGELOG.md, filter/metadata_lastmodified.go, filter/metadata_lastmodified_test.go
This is an update of PR #131. It adds the test case in which the date is set but it is zero.
=> fix: cover all MetadataLastModified test case

CHANGELOG.md, help_markdown.go
The Glamour library already manages the newlines properly.
=> fix: PrintHelp wrongly insert newlines after dots

stats_test.go
Remove `flag.Parse()` call inside the `TestStatsDumper` to avoid an occasional race condition.
The flags are automatically parsed by the testing library, [ref1](https://github.com/golang/go/issues/38952), [ref2](https://pkg.go.dev/testing#hdr-Main).
=> fix: occasional race on stats_test

filter/dedup.go
Not printable `\x1e` character was not shown in the Dedup filter documentation.
=> doc: update KeySeparator default value in Dedup

input/tcp.go, input/tcp_test.go
Fix some missing `Close` in `TCP` input and remove a flaky test. No need to fix it since this test (`TestTCPStopChunk`) only made sense if the closure semantics of the `TCP` input, once `TCP.Stop()` is called, was to wait for the currently bound connection, if any, to be closed by the client. But since this is not how  this input works, (i.e. it closes as soon as possible after receiving `Stop`) fixing the test to make it work would make it be the same as `TestTCPChunks`.
=> Remove flaky test from TCP input

CHANGELOG.md, filter/expand_list.go, filter/expand_list_test.go
The current implementation of the `ExpandList` filter has a strange behavior in the situation the input list is empty.
In particular the filter consider the empty list as a list with 1 empty elements, namely `""` -> `[""]`
For instance, consider the case in which the filter is configured to expand the list in the field `source` in such a way that `0 index` -> `f1` and `1 index` -> `f2`.
Thus, if we provide the following input record:
|f1|f2|source|
|--|---|---------|
|foo|bar||
The filter produces the corresponding output:
|f1|f2|source|
|--|---|---------|
||bar||
This PR changes the behavior of the filter and in the aforementioned situation it simply does nothing and forward. Thus, the output of the previous example will be:
|f1|f2|source|
|--|---|---------|
|foo|bar||
1. List all steps …
=> fix: ExpandList behaviour if source is empty

CHANGELOG.md, config.go
To trigger the problem fixed by this change you have to:
- use a component with a Config structure using a map
- somewhat manage to create, in the same process, at least 2 baker
topologies using this component, each of which having different keys in
the map.
Even if not impossible, it would be rather improbable to have this in a
normal production usage. However it's really easy to trigger with tests!
`go test -run foo` does exactly that`. It launches X times the tests
containing foo in their name, all in the same process.
The problem arises when copying the Desc.Config (an interface{}) to the
DecodedConfig field of the final component instance (also an
interface{}). The DecodedConfig is then used as destination for TOML
decoding.  But the thing is that the TOML library we're using merges …
=> Clone configs instead of reusing pointer in desc

input/kcl.go
When there's a checkpointing error, we were not logging the cause.
=> input: kcl: add error to checkpointing error log

Makefile
Small fix on `gen-components` task: use `@main` instead of `@latest` in go get. Indeed, the `@latest` tag gets the latest release of the package instead of the latest version of the `main` branch.
=> fix: force go get of the baker main branch

go.mod
zip_agnostic makes use of `io.NopCloser`, which is a 1.16 feature.
Bumps Go version to 1.16 in go.mod
Let the pipelines run unit tests (change done via the web GUI).
=> Require Go 1.16

CHANGELOG.md, filter/all.go, filter/count_and_tag.go, filter/count_and_tag_test.go, filter/external_match.go, filter/external_match_test.go, stats_test.go, testutil/mock_metrics.go
Add a new filter, called `CountAndTag`. This filter publishes a metric that simply counts all records that pass through, and breaks them down, with metrics tags, by the value of a configured field.
Records having an empty string as `Field` value are counted nonetheless, using the value configured as `DefaultValue` as tag value
note: performance has been measured on a real-life pipeline, with datadog as metrics client implementation, and both cpu and memory were dominated by io (reading from input, writing to output) so we consider the performance as acceptable, in fact it greatly depends on the metrics client implementation itself, since there will be one call per record, per filter chain process. That's not a problem per se since metrics libraries are optimized for this exact use case. …
=> Add count and tag filter

CHANGELOG.md, input/sqs.go, input/sqs_test.go
Queue prefixes could lead to undesired behaviour, this new option makes the use strict to specific queues
Implementing a new config QueueNames to sqs Input. 
When using deadletter queues in SQS we often do not expect Baker to read from that queue, but because the default is to add the suffix to the queue name to indicate is a dead-letter queue, Baker ends up reading from that queue too.
With this new parameter we are strict to which queues we want to read from without surprises if some queue with similar name is created.
Change the QueuePrefixes parameter to QueueNames - it should behave the same way, but it will listen only to that specific queue.
_This section contains a list of checklists for common uses, please delete the checklists that are useless for your current use case (or add …
=> Implementing a new config QueueNames to sqs Input.

baker_cli.go
…the same flag
https://github.com/DataDog/dd-trace-go/issues/1153
Baker library conflicts with dd-trace-go library because of dependencies on glog.
glog also defines the flag v
`panic: /var/folders/yg/7bk34drs0zjfsb9b_r_1sykr0000gn/T/go-build2940344100/b001/exe/main flag redefined: v
`
This PR make possible to use both libraries side by side.
It's not possible to send PR to glog because it's a Google internal library that does not accept contributions. But dd-trace-go and also [ristretto](https://github.com/SemanticSugar/baker/blob/main/go.mod#L11) have dependencies on it. 
Try to import both libraries at the same time:
```
package main
import (
"fmt"
"github.com/AdRoll/baker"
"gopkg.in/DataDog/dd-trace-go.v1/ddtrace/tracer"
)
func main() {
tracer.Start(
tracer.WithEnv("testing"), …
```
=> Creates a new flagset to avoid conflit with other libraries that use the same flag
