AdRoll/baker

CHANGELOG.md, filter/timestamp.go, filter/timestamp_range.go, filter/timestamp_test.go
Add timestamp filter. This filter sets, for all records it processes, a field to unix epoch timestamp.
The field is configurable
**WARNING**
Merging this should be syncronized with the corresponding removal on adroll-private repo
=> Add timestamp filter

.github/workflows/go.yml, CHANGELOG.md, Makefile, examples/advanced/components.go, go.mod, go.sum, output/sqlite.go, output/sqlite_cgo.go, output/sqlite_test.go
=> Add sqlite output

README.md
Document component configuration and field struct tags in the README
=> README: document component config + struct tags

CHANGELOG.md, config.go
This is a leftover of a previous refactoring
=> Remove RawChanSize

api.go, baker.go, config.go, desc.go, filter/all.go, filter/clausefilter.go, filter/clear_fields.go, filter/concatenate.go, filter/notnull.go, filter/regex_match.go, filter/replace_fields.go, input/all.go, logline.go, metrics/all.go, output/all.go, output/websocket.go, output/websocket/client.go, output/websocket/server.go, testutil/golden.go, topology.go, upload/all.go
Improve API docs for https://pkg.go.dev/github.com/AdRoll/baker
=> Improve API documentation

CHANGELOG.md, baker.go, examples/advanced/main.go, examples/basic/main.go, examples/filtering/main.go, examples/metrics/main.go, examples/sharding/main.go
Remove duration parameter from `baker.Main`
=> Remove duration from main

Makefile, README.md, content/en/docs/Core concepts/_index.md, content/en/docs/Core concepts/toml.md, docs/docs/core-concepts/index.html, docs/docs/core-concepts/index.xml, docs/docs/core-concepts/toml/index.html, docs/docs/getting-started/index.html, docs/docs/index.html, docs/index.xml, docs/sitemap.xml, package-lock.json, package.json, yarn.lock
Add the "Pipeline configuration" doc page to the website
=> Add doc page for pipeline configuration (by TOML file)

content/en/docs/Core concepts/record_implementation.md
Document how to implement a custom `Record`
=> doc: record implementation

Dockerfile, Dockerfile.base, Makefile, README.md
Add Dockerfile.base and Dockerfile, some makefile targets to use them and update the README for development and running the website server.
1. `make docker-dev`
2. point your browser to http://locahost:1313/baker
3. modify `content/en/docs/Core concepts/toml.md`
4. the browser page should update
or
1. `make docker-run-prod`
2. point your browser to http://locahost/baker # port 80
=> Doc dockerfile

content/en/docs/Core concepts/concurrency.md
How to tune concurrency in baker
=> doc: tuning concurrency

content/en/docs/Core concepts/metrics.md
Add metrics sections to baker docs website.
=> content: add metrics.md

content/en/_index.html, content/en/docs/Core concepts/_index.md, content/en/docs/Core concepts/record_implementation.md, content/en/docs/Core concepts/sharding.md, content/en/docs/Core concepts/toml.md, content/en/docs/Getting started/_index.md, content/en/docs/How To/_index.md, content/en/docs/How To/baker_components.md, content/en/docs/How To/custom_record.md, content/en/docs/_index.md
* Small intro to the documentation
* `baker.Components` doc page
=> add intro and baker.Components pages

content/en/docs/Core concepts/sharding.md, content/en/docs/How To/sharding.md
Add sharding both in core concepts and how to sections
=> Doc core sharding

content/en/docs/How To/create_filter.md
=> doc: How to create a filter

content/en/docs/How To/create_input.md
Doc: how-to create an input component
=> doc: how to create an input

content/en/docs/How To/create_upload.md
doc: how to create an upload component
=> doc: how to create an upload

README.md, filter/clausefilter.go, filter/clear_fields.go, tutorials/basic/README.md, tutorials/basic/main.go, tutorials/basic/topology.toml
This is part of the basic tutorial PR https://github.com/AdRoll/baker/pull/85 , adding the example program files to the `main` branch
=> Basic tutorial files

content/en/docs/How Tos/create_filter.md
=> doc: how to test filters

content/en/docs/How Tos/create_output.md
=> doc: how to test outputs

content/en/docs/How Tos/create_upload.md
=> doc: how to test uploads

content/en/docs/How Tos/create_input.md
=> doc: how to test inputs

content/en/docs/Components/_index.md
Add no_list again in components list page
=> Re-add no_list in components list page

input/sqs.go
Fix the `panic: send on closed channel` happening very regularly when stopping a running pipeline with the SQS input with CTRL-C.
=> input: sqs: fix send on closed channel

baker_cli.go
`MainCLI` renders the markdown help in the terminal
=> MainCLI: format the help as markdown

content/en/docs/Getting started/_index.md
Improve the "Getting started" page with a more detailed example
=> improve getting started page

content/en/docs/Performance/_index.md
Add intro on performance page, explaining baker aimed at performance from the start
=> Performance page: add intro with performance design

assets/scss/_styles_project.scss, config.toml, content/en/_index.html
=> Improve the home page structure and content

CHANGELOG.md, filter/string_match.go, filter/string_match_test.go
Add StringMatch filter which discards/keeps records based on the result of string comparisons.
=> filter: add StringMatch

.codecov.yml, .github/workflows/go.yml, .gitignore, Makefile, README.md
Add a step in the github action that sends coverage report to codecov
=> Add codecov

content/en/docs/Components/Filters/ClauseFilter.md, content/en/docs/Components/Filters/ClearFields.md, content/en/docs/Components/Filters/Concatenate.md, content/en/docs/Components/Filters/NotNull.md, content/en/docs/Components/Filters/RegexMatch.md, content/en/docs/Components/Filters/ReplaceFields.md, content/en/docs/Components/Filters/SetStringFromURL.md, content/en/docs/Components/Filters/StringMatch.md, content/en/docs/Components/Filters/Timestamp.md, content/en/docs/Components/Filters/TimestampRange.md, content/en/docs/Components/Inputs/KCL.md, content/en/docs/Components/Inputs/Kinesis.md, content/en/docs/Components/Inputs/List.md, content/en/docs/Components/Inputs/SQS.md, content/en/docs/Components/Inputs/TCP.md, content/en/docs/Components/Outputs/DynamoDB.md, content/en/docs/Components/Outputs/FileWriter.md, content/en/docs/Components/Outputs/Nop.md, content/en/docs/Components/Outputs/OpLog.md, content/en/docs/Components/Outputs/Stats.md, content/en/docs/Components/Outputs/WebSocket.md, content/en/docs/Components/Uploads/S3.md, utils/generate-components-pages/main.go
add a header to each components page linking the API section for the component family
=> Link docs to api

.github/workflows/go.yml, .github/workflows/win.yml, help_markdown.go, term.go, term_windows.go
This PR is for support build under win arch. We can close #113
=> Windows build

content/en/docs/How Tos/baker_components.md, content/en/docs/How Tos/custom_record.md
To be merged after #111
FIxes documentation after #111 (changes from function to slice of FieldName) 
=> Fieldname doc change

content/en/docs/How Tos/pipeline_configuration.md
we missed a bunch of conf sections
=> Update Pipeline Configuration with missing confs

content/en/docs/How Tos/baker_components.md, content/en/docs/How Tos/pipeline_configuration.md
Update the documentation with the new validation feature (#122).
=> doc: add validation section in the TOML

Dockerfile, Makefile, README.md
Update the website building system. Provided make commands are:
- `setup` Setup Hugo locally 
- `dev` Run local server to check you content while writing
- `build` Build the static files of the website
- `docker-setup` Setup Hugo with docker
- `docker-dev` Use docker for baker website development
- `docker-build` Use docker for build the baker website
- `docker-run-prod` Use docker for running the website on port :80
- `clear` Delete all created files
Finally with `make clear` all the files created by Hugo and the other setup commands are deleted
Running with docker 
```
make docker-setup
make docker-dev
```
Running locally with
```
make setup
make dev
```
=> refactor: site building

.github/workflows/linux.yml, .github/workflows/win.yml
Configure the CI cache as suggested [here](https://github.com/actions/cache/blob/main/examples.md#go---modules).
The previous configuration restore, all the time, an empty cache.
=> chore: fix CI cache

examples/filtering/filter.go
Extend the refactoring of #148 for the example filter `LazyFilter`.
=> refactor: remove nil check example filter

CHANGELOG.md, input/list.go, input/list_test.go
Add test cases for input list in 'HTTP' mode.
The PR fixes also two bugs:
- list of HTTP files were not correctly downloaded
- HTTP get does not manage status codes (e.g. 404)
=> feat: improve List input tests

content/en/docs/How Tos/metrics.md
=> website: update metrics doc

content/en/docs/Core concepts/_index.md, content/en/docs/How Tos/custom_record.md, content/en/docs/How Tos/record_and_logline.md
1. clarify the documentation of the record validation through code or TOML 
2. update the documentation of the record customization
=> website: improve record validation doc

metrics.go
Update the documentation of the `MetricsBag`.
=> doc: update MetricsBag

.codecov.yml, .github/workflows/cover.yml, .github/workflows/coverage.yml, .github/workflows/linux.yml, .github/workflows/win.yml, Makefile
This PR is the result of having investigated if cross coverage can add some benefit to the project.
The answer is no:
- first it's not a good practice in Go due to the essence of Go packages, a Go package encapsulates private behavior which no package one (apart possibly the one it's defined in) should rely upon. A package public API can and should be tested in the same package this API is defined.
- it happens that code in Baker that doesn't appear in coverage report is not tested, even by other packages, so even cross coverage would not artificially increase the coverage number.
Given the previous reasons, I've just somewhat refined a bit the CI scripts with respect to code coverage:
- coverage is now performed in its own Github action workflow, in parallel with the other workflows
- …
=> CI: coverage report in own workflow

CHANGELOG.md
Once merged the commit will be tagged with `v0.1.0-alpha`.
=> Update CHANGELOG.md for v0.1.0-alpha 

CHANGELOG.md, filter/all.go, filter/crypt.go, filter/crypt_test.go, go.mod, go.sum
=> feat: add crypt filter

bench_test.go
These two fields need to be both or none, so it caused the call to err.
Describe what this pull request does.
=> Benchmarks were setting FieldByName but not FieldNames

content/en/docs/Performance/_index.md
=> content/docs/perf: fix typo

filter/regex_match.go, filter/regex_match_test.go
Add InvertMatch setting to RegexMatch filter 
=> Regex match/invert

tutorials/basic/README.md
Small fix to use the .io top level domain instead of .com (current address leads to a linkedin page).
=> Fix tutorial URL

content/en/docs/Components/Inputs/SQS.md
Updates documentation to website.
=> Add QueueNames parameter to documentation

CHANGELOG.md, input/kcl.go
Make LeaseDuration parameter configuration on the KCL input.
=> input: in KCL, make LeaseDuration configurable
